--
-- PostgreSQL database dump
--

\restrict KtnqXAco1GeYgGdpkvfctffBiz9mKXGWKDjt5SrAUhoDmAZG5JEfsCdEajXTX7u

-- Dumped from database version 14.22 (Ubuntu 14.22-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.22 (Ubuntu 14.22-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: company_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_documents (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    description text,
    category text DEFAULT 'Lainnya'::text NOT NULL,
    file_name text NOT NULL,
    file_type text NOT NULL,
    file_size integer,
    file_data text NOT NULL,
    branch_id uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by uuid
);


--
-- Name: expense_category_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expense_category_mapping (
    id bigint NOT NULL,
    category_name text NOT NULL,
    account_id text NOT NULL,
    account_code text NOT NULL,
    account_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: expense_category_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.expense_category_mapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expense_category_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_unit_conversions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_unit_conversions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    item_type text NOT NULL,
    item_id uuid NOT NULL,
    unit_name text NOT NULL,
    conversion_qty numeric(15,4) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT item_unit_conversions_conversion_qty_check CHECK ((conversion_qty > (0)::numeric)),
    CONSTRAINT item_unit_conversions_item_type_check CHECK ((item_type = ANY (ARRAY['material'::text, 'product'::text])))
);


--
-- Name: material_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.material_payments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    material_id uuid NOT NULL,
    amount numeric NOT NULL,
    payment_date timestamp with time zone DEFAULT now() NOT NULL,
    cash_account_id text NOT NULL,
    notes text,
    journal_entry_id uuid,
    created_by uuid,
    created_by_name text DEFAULT ''::text NOT NULL,
    branch_id uuid,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT material_payments_amount_check CHECK ((amount > (0)::numeric))
);


--
-- Name: sales_commission_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_commission_settings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    sales_id uuid NOT NULL,
    commission_type text NOT NULL,
    commission_value numeric DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    branch_id uuid,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT sales_commission_settings_commission_type_check CHECK ((commission_type = ANY (ARRAY['percentage'::text, 'fixed'::text]))),
    CONSTRAINT sales_commission_settings_commission_value_check CHECK ((commission_value >= (0)::numeric))
);


--
-- Name: transaction_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaction_payments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    transaction_id text NOT NULL,
    payment_date timestamp with time zone DEFAULT now() NOT NULL,
    amount numeric NOT NULL,
    payment_method text DEFAULT 'cash'::text,
    account_id text,
    account_name text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    notes text,
    reference_number text,
    paid_by_user_id uuid,
    paid_by_user_name text DEFAULT ''::text NOT NULL,
    paid_by_user_role text,
    created_at timestamp with time zone DEFAULT now(),
    created_by uuid,
    status text DEFAULT 'active'::text,
    cancelled_at timestamp with time zone,
    cancelled_by uuid,
    cancelled_reason text,
    branch_id uuid,
    CONSTRAINT transaction_payments_amount_check CHECK ((amount > (0)::numeric)),
    CONSTRAINT transaction_payments_payment_method_check CHECK ((payment_method = ANY (ARRAY['cash'::text, 'bank_transfer'::text, 'check'::text, 'digital_wallet'::text, 'transfer'::text]))),
    CONSTRAINT transaction_payments_status_check CHECK ((status = ANY (ARRAY['active'::text, 'cancelled'::text, 'deleted'::text])))
);


--
-- Name: v_customer_summaries; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.v_customer_summaries AS
 WITH order_summary AS (
         SELECT t.customer_id,
            (count(*))::integer AS order_count,
            max(t.order_date) AS last_order_date
           FROM public.transactions t
          WHERE ((COALESCE(t.is_voided, false) = false) AND (COALESCE(t.is_cancelled, false) = false) AND (t.customer_id IS NOT NULL))
          GROUP BY t.customer_id
        ), receivable_summary AS (
         SELECT r.customer_id,
            sum(COALESCE(r.amount, (0)::numeric)) AS total_piutang,
            sum(GREATEST((COALESCE(r.amount, (0)::numeric) - COALESCE(r.paid_amount, (0)::numeric)), (0)::numeric)) AS sisa_piutang,
            (count(*) FILTER (WHERE (GREATEST((COALESCE(r.amount, (0)::numeric) - COALESCE(r.paid_amount, (0)::numeric)), (0)::numeric) > (0)::numeric)))::integer AS jumlah_piutang,
            min(r.due_date) FILTER (WHERE (GREATEST((COALESCE(r.amount, (0)::numeric) - COALESCE(r.paid_amount, (0)::numeric)), (0)::numeric) > (0)::numeric)) AS jatuh_tempo_terdekat
           FROM public.receivables r
          WHERE ((r.status = ANY (ARRAY['pending'::text, 'partial'::text])) AND (r.customer_id IS NOT NULL))
          GROUP BY r.customer_id
        ), last_gallon_movement AS (
         SELECT DISTINCT ON (gm.customer_id) gm.customer_id,
            gm.delta AS last_gallon_delta,
            gm.type AS last_gallon_type,
            gm.created_at AS last_gallon_change_at
           FROM public.gallon_movements gm
          WHERE (gm.customer_id IS NOT NULL)
          ORDER BY gm.customer_id, gm.created_at DESC
        )
 SELECT c.id,
    c.name,
    c.phone,
    c.address,
    c.latitude,
    c.longitude,
    c.full_address,
    c.store_photo_url,
    c.jumlah_galon_titip,
    c.classification,
    c.branch_id,
    COALESCE(c."createdAt", c.createdat, now()) AS created_at,
    COALESCE(os.order_count, 0) AS order_count,
    os.last_order_date,
    COALESCE(rs.total_piutang, (0)::numeric) AS total_piutang,
    COALESCE(rs.sisa_piutang, (0)::numeric) AS sisa_piutang,
    COALESCE(rs.jumlah_piutang, 0) AS jumlah_piutang,
    rs.jatuh_tempo_terdekat,
    lgm.last_gallon_delta,
    lgm.last_gallon_type,
    lgm.last_gallon_change_at
   FROM (((public.customers c
     LEFT JOIN order_summary os ON ((os.customer_id = c.id)))
     LEFT JOIN receivable_summary rs ON ((rs.customer_id = c.id)))
     LEFT JOIN last_gallon_movement lgm ON ((lgm.customer_id = c.id)));


--
-- Name: company_documents company_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_documents
    ADD CONSTRAINT company_documents_pkey PRIMARY KEY (id);


--
-- Name: expense_category_mapping expense_category_mapping_category_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_category_mapping
    ADD CONSTRAINT expense_category_mapping_category_name_key UNIQUE (category_name);


--
-- Name: expense_category_mapping expense_category_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_category_mapping
    ADD CONSTRAINT expense_category_mapping_pkey PRIMARY KEY (id);


--
-- Name: item_unit_conversions item_unit_conversions_item_type_item_id_unit_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_unit_conversions
    ADD CONSTRAINT item_unit_conversions_item_type_item_id_unit_name_key UNIQUE (item_type, item_id, unit_name);


--
-- Name: item_unit_conversions item_unit_conversions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_unit_conversions
    ADD CONSTRAINT item_unit_conversions_pkey PRIMARY KEY (id);


--
-- Name: material_payments material_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_payments
    ADD CONSTRAINT material_payments_pkey PRIMARY KEY (id);


--
-- Name: sales_commission_settings sales_commission_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_commission_settings
    ADD CONSTRAINT sales_commission_settings_pkey PRIMARY KEY (id);


--
-- Name: transaction_payments transaction_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_payments
    ADD CONSTRAINT transaction_payments_pkey PRIMARY KEY (id);


--
-- Name: idx_company_documents_branch; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_documents_branch ON public.company_documents USING btree (branch_id);


--
-- Name: idx_company_documents_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_documents_category ON public.company_documents USING btree (category);


--
-- Name: idx_expense_category_mapping_category_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_expense_category_mapping_category_name ON public.expense_category_mapping USING btree (category_name);


--
-- Name: idx_item_unit_conversions_item; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_item_unit_conversions_item ON public.item_unit_conversions USING btree (item_type, item_id);


--
-- Name: idx_material_payments_branch_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_material_payments_branch_id ON public.material_payments USING btree (branch_id);


--
-- Name: idx_material_payments_material_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_material_payments_material_id ON public.material_payments USING btree (material_id);


--
-- Name: idx_material_payments_payment_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_material_payments_payment_date ON public.material_payments USING btree (payment_date);


--
-- Name: idx_sales_commission_settings_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sales_commission_settings_active ON public.sales_commission_settings USING btree (is_active);


--
-- Name: idx_sales_commission_settings_branch_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sales_commission_settings_branch_id ON public.sales_commission_settings USING btree (branch_id);


--
-- Name: idx_sales_commission_settings_sales_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sales_commission_settings_sales_id ON public.sales_commission_settings USING btree (sales_id);


--
-- Name: idx_transaction_payments_branch_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transaction_payments_branch_id ON public.transaction_payments USING btree (branch_id);


--
-- Name: idx_transaction_payments_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transaction_payments_date ON public.transaction_payments USING btree (payment_date);


--
-- Name: idx_transaction_payments_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transaction_payments_status ON public.transaction_payments USING btree (status);


--
-- Name: idx_transaction_payments_transaction_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transaction_payments_transaction_id ON public.transaction_payments USING btree (transaction_id);


--
-- Name: item_unit_conversions trg_item_unit_conversions_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_item_unit_conversions_updated_at BEFORE UPDATE ON public.item_unit_conversions FOR EACH ROW EXECUTE FUNCTION public.set_item_unit_conversions_updated_at();


--
-- Name: expense_category_mapping expense_category_mapping_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expense_category_mapping
    ADD CONSTRAINT expense_category_mapping_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: material_payments material_payments_branch_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_payments
    ADD CONSTRAINT material_payments_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id);


--
-- Name: material_payments material_payments_cash_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_payments
    ADD CONSTRAINT material_payments_cash_account_id_fkey FOREIGN KEY (cash_account_id) REFERENCES public.accounts(id);


--
-- Name: material_payments material_payments_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_payments
    ADD CONSTRAINT material_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id);


--
-- Name: material_payments material_payments_journal_entry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_payments
    ADD CONSTRAINT material_payments_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id);


--
-- Name: material_payments material_payments_material_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.material_payments
    ADD CONSTRAINT material_payments_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materials(id);


--
-- Name: sales_commission_settings sales_commission_settings_branch_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_commission_settings
    ADD CONSTRAINT sales_commission_settings_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id);


--
-- Name: sales_commission_settings sales_commission_settings_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_commission_settings
    ADD CONSTRAINT sales_commission_settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id);


--
-- Name: sales_commission_settings sales_commission_settings_sales_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_commission_settings
    ADD CONSTRAINT sales_commission_settings_sales_id_fkey FOREIGN KEY (sales_id) REFERENCES public.profiles(id);


--
-- Name: transaction_payments transaction_payments_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_payments
    ADD CONSTRAINT transaction_payments_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: transaction_payments transaction_payments_branch_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_payments
    ADD CONSTRAINT transaction_payments_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id);


--
-- Name: transaction_payments transaction_payments_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_payments
    ADD CONSTRAINT transaction_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id);


--
-- Name: transaction_payments transaction_payments_paid_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_payments
    ADD CONSTRAINT transaction_payments_paid_by_user_id_fkey FOREIGN KEY (paid_by_user_id) REFERENCES public.profiles(id);


--
-- Name: transaction_payments transaction_payments_transaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_payments
    ADD CONSTRAINT transaction_payments_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id) ON DELETE CASCADE;


--
-- Name: company_documents; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.company_documents ENABLE ROW LEVEL SECURITY;

--
-- Name: company_documents company_documents_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY company_documents_delete ON public.company_documents FOR DELETE TO authenticated USING (true);


--
-- Name: company_documents company_documents_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY company_documents_insert ON public.company_documents FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: company_documents company_documents_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY company_documents_select ON public.company_documents FOR SELECT TO authenticated USING (true);


--
-- Name: company_documents company_documents_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY company_documents_update ON public.company_documents FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: expense_category_mapping; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.expense_category_mapping ENABLE ROW LEVEL SECURITY;

--
-- Name: expense_category_mapping expense_category_mapping_allow_all; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY expense_category_mapping_allow_all ON public.expense_category_mapping TO authenticated USING (true) WITH CHECK (true);


--
-- Name: material_payments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.material_payments ENABLE ROW LEVEL SECURITY;

--
-- Name: material_payments material_payments_allow_all; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY material_payments_allow_all ON public.material_payments TO authenticated USING (true) WITH CHECK (true);


--
-- Name: sales_commission_settings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.sales_commission_settings ENABLE ROW LEVEL SECURITY;

--
-- Name: sales_commission_settings sales_commission_settings_allow_all; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY sales_commission_settings_allow_all ON public.sales_commission_settings TO authenticated USING (true) WITH CHECK (true);


--
-- Name: transaction_payments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.transaction_payments ENABLE ROW LEVEL SECURITY;

--
-- Name: transaction_payments transaction_payments_allow_all; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY transaction_payments_allow_all ON public.transaction_payments TO authenticated USING (true) WITH CHECK (true);


--
-- PostgreSQL database dump complete
--

\unrestrict KtnqXAco1GeYgGdpkvfctffBiz9mKXGWKDjt5SrAUhoDmAZG5JEfsCdEajXTX7u

